[package]
name = "fdupesrs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
blake3 = "1.5.4"
clap = { version = "4.5.20", features = ["derive"] }
rayon = "1.10.0"
walkdir = "2.5.0"
