[package]
name = "drupes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
blake3 = "1.5.4"
clap = { version = "4.5.20", features = ["derive", "wrap_help"] }
jwalk = "0.8.1"
rayon = "1.10.0"
size = "0.4.1"
nix = { version = ">=0.29.0", features = ["fs"] }
